### ISSUE TITLE
Vector2 movement speed?

### ISSUE THREAD

**Issue by ogrotten** [samsface/godot-pokemon#2]
Web dev (JS ecosystem) by day, but new to godot. I'm trying to get my bearings with this demo project. 

I want to increase the move speed of the player and other stuff. I dug around looking for a constant "speed" or "velocity" or something, to no avail. All the info I'm seeing on increasing speed says multiply the values of the Vector2 arguments, but that results in a dictionary error?

![image](https://github.com/samsface/godot-pokemon/assets/8119012/77768a67-778c-4c2c-86d5-85fe9078f90f)

I it looks like you're just using stock classes and methods so I cant' tell why this is failing. Any suggestions?

Thanks for doing this, and thanks for the tutorial series.

**Comment by samsface** [comment]
The speeds were hardcoded. Pushed a small commit to make these configurable, hope it helps:
https://github.com/samsface/godot-pokemon/commit/928c1338f1c5d5532a5dbf9e0cfb52d2fb95ccb9

**Comment by ogrotten** [comment]
Hey dude thanks for the change! Looking at the diff helps as well, clearly more than one way to move a guy.
